regtest=1
server=1
txindex=1
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
rpcuser=bitcoin
rpcpassword=bitcoin
fallbackfee=0.0001
# Allow bare connections from Fulcrum
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
